/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiRunsRouteImport } from './routes/api/runs'
import { Route as ApiTriggerRouteImport } from './routes/api/trigger'
import { Route as ApiVetoRouteImport } from './routes/api/veto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRoute = ApiRunsRouteImport.update({
  id: '/api/runs',
  path: '/api/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTriggerRoute = ApiTriggerRouteImport.update({
  id: '/api/trigger',
  path: '/api/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVetoRoute = ApiVetoRouteImport.update({
  id: '/api/veto',
  path: '/api/veto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cron': typeof ApiCronRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/trigger': typeof ApiTriggerRoute
  '/api/veto': typeof ApiVetoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cron': typeof ApiCronRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/trigger': typeof ApiTriggerRoute
  '/api/veto': typeof ApiVetoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cron': typeof ApiCronRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/trigger': typeof ApiTriggerRoute
  '/api/veto': typeof ApiVetoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/cron'
    | '/api/dashboard'
    | '/api/runs'
    | '/api/trigger'
    | '/api/veto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/cron'
    | '/api/dashboard'
    | '/api/runs'
    | '/api/trigger'
    | '/api/veto'
  id:
    | '__root__'
    | '/'
    | '/api/cron'
    | '/api/dashboard'
    | '/api/runs'
    | '/api/trigger'
    | '/api/veto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCronRoute: typeof ApiCronRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiRunsRoute: typeof ApiRunsRoute
  ApiTriggerRoute: typeof ApiTriggerRoute
  ApiVetoRoute: typeof ApiVetoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs': {
      id: '/api/runs'
      path: '/api/runs'
      fullPath: '/api/runs'
      preLoaderRoute: typeof ApiRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trigger': {
      id: '/api/trigger'
      path: '/api/trigger'
      fullPath: '/api/trigger'
      preLoaderRoute: typeof ApiTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/veto': {
      id: '/api/veto'
      path: '/api/veto'
      fullPath: '/api/veto'
      preLoaderRoute: typeof ApiVetoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCronRoute: ApiCronRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiRunsRoute: ApiRunsRoute,
  ApiTriggerRoute: ApiTriggerRoute,
  ApiVetoRoute: ApiVetoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
