/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBrandsRouteImport } from './routes/api/brands'
import { Route as ApiCronRouteImport } from './routes/api/cron'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiHuntsRouteImport } from './routes/api/hunts'
import { Route as ApiRunsRouteImport } from './routes/api/runs'
import { Route as ApiSizeGroupsRouteImport } from './routes/api/size-groups'
import { Route as ApiTriggerRouteImport } from './routes/api/trigger'
import { Route as ApiVetoRouteImport } from './routes/api/veto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandsRoute = ApiBrandsRouteImport.update({
  id: '/api/brands',
  path: '/api/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHuntsRoute = ApiHuntsRouteImport.update({
  id: '/api/hunts',
  path: '/api/hunts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRoute = ApiRunsRouteImport.update({
  id: '/api/runs',
  path: '/api/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSizeGroupsRoute = ApiSizeGroupsRouteImport.update({
  id: '/api/size-groups',
  path: '/api/size-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTriggerRoute = ApiTriggerRouteImport.update({
  id: '/api/trigger',
  path: '/api/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVetoRoute = ApiVetoRouteImport.update({
  id: '/api/veto',
  path: '/api/veto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/brands': typeof ApiBrandsRoute
  '/api/cron': typeof ApiCronRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/hunts': typeof ApiHuntsRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/size-groups': typeof ApiSizeGroupsRoute
  '/api/trigger': typeof ApiTriggerRoute
  '/api/veto': typeof ApiVetoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/brands': typeof ApiBrandsRoute
  '/api/cron': typeof ApiCronRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/hunts': typeof ApiHuntsRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/size-groups': typeof ApiSizeGroupsRoute
  '/api/trigger': typeof ApiTriggerRoute
  '/api/veto': typeof ApiVetoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/brands': typeof ApiBrandsRoute
  '/api/cron': typeof ApiCronRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/api/hunts': typeof ApiHuntsRoute
  '/api/runs': typeof ApiRunsRoute
  '/api/size-groups': typeof ApiSizeGroupsRoute
  '/api/trigger': typeof ApiTriggerRoute
  '/api/veto': typeof ApiVetoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/brands'
    | '/api/cron'
    | '/api/dashboard'
    | '/api/hunts'
    | '/api/runs'
    | '/api/size-groups'
    | '/api/trigger'
    | '/api/veto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/brands'
    | '/api/cron'
    | '/api/dashboard'
    | '/api/hunts'
    | '/api/runs'
    | '/api/size-groups'
    | '/api/trigger'
    | '/api/veto'
  id:
    | '__root__'
    | '/'
    | '/api/brands'
    | '/api/cron'
    | '/api/dashboard'
    | '/api/hunts'
    | '/api/runs'
    | '/api/size-groups'
    | '/api/trigger'
    | '/api/veto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBrandsRoute: typeof ApiBrandsRoute
  ApiCronRoute: typeof ApiCronRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  ApiHuntsRoute: typeof ApiHuntsRoute
  ApiRunsRoute: typeof ApiRunsRoute
  ApiSizeGroupsRoute: typeof ApiSizeGroupsRoute
  ApiTriggerRoute: typeof ApiTriggerRoute
  ApiVetoRoute: typeof ApiVetoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brands': {
      id: '/api/brands'
      path: '/api/brands'
      fullPath: '/api/brands'
      preLoaderRoute: typeof ApiBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hunts': {
      id: '/api/hunts'
      path: '/api/hunts'
      fullPath: '/api/hunts'
      preLoaderRoute: typeof ApiHuntsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs': {
      id: '/api/runs'
      path: '/api/runs'
      fullPath: '/api/runs'
      preLoaderRoute: typeof ApiRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/size-groups': {
      id: '/api/size-groups'
      path: '/api/size-groups'
      fullPath: '/api/size-groups'
      preLoaderRoute: typeof ApiSizeGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trigger': {
      id: '/api/trigger'
      path: '/api/trigger'
      fullPath: '/api/trigger'
      preLoaderRoute: typeof ApiTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/veto': {
      id: '/api/veto'
      path: '/api/veto'
      fullPath: '/api/veto'
      preLoaderRoute: typeof ApiVetoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBrandsRoute: ApiBrandsRoute,
  ApiCronRoute: ApiCronRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  ApiHuntsRoute: ApiHuntsRoute,
  ApiRunsRoute: ApiRunsRoute,
  ApiSizeGroupsRoute: ApiSizeGroupsRoute,
  ApiTriggerRoute: ApiTriggerRoute,
  ApiVetoRoute: ApiVetoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
